version: 0.2

env:
  parameter-store:
    DOCKER_CACHE_USERNAME: handel.global.jfrog_docker_username
    DOCKER_CACHE_PASSWORD: handel.global.jfrog_docker_password
    DOCKER_CACHE_REGISTRY: handel.global.jfrog_docker_registry

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      # Login to docker cache
      - docker login $DOCKER_CACHE_REGISTRY -u $DOCKER_CACHE_USERNAME -p $DOCKER_CACHE_PASSWORD
  build:
    commands:
      - docker build -t infohub --build-arg REGISTRY="$DOCKER_CACHE_REGISTRY" .
  post_build:
    commands:
      - export ecrImage="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/infohub:$HANDEL_PIPELINE_NAME"
      - docker tag infohub $ecrImage
      - docker push $ecrImage

artifacts:
  files:
  - 'handel.yml'