
version: 1

name: infohub

pipelines:
  dev:
    phases:
      - type: github
        name: Github
        owner: byu-oit
        repo: infohub
        branch: dev
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:2.0
      - type: handel
        name: Deploy
        environments_to_deploy:
          - dev
  prd:
    phases:
      - type: github
        name: Github
        owner: byu-oit
        repo: infohub
        branch: aws-prd
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:2.0
      - type: handel
        name: Deploy
        environments_to_deploy:
          - dev